- name: Install app on new web server
  hosts: virtual-machines
  remote_user: ec2-user

  tasks:
    - name: Install Git
      ansible.builtin.yum:
        name: git
        state: present
      become: yes

    - name: Install Python3
      ansible.builtin.yum:
        name: python3
        state: present
      become: yes

    - name: Install Poetry
      ansible.builtin.shell:
        cmd: curl -sSL https://install.python-poetry.org | python3 -
      become: yes