name: Continuous Integration
on: [push, pull_request]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Build test docker image
      run: docker build --target test -t todo_app:test .

    - name: Run tests
      run: docker run --rm todo_app:test